apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 3
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: 970355526286.dkr.ecr.us-east-1.amazonaws.com/nodejs:{{TAG}}
# {{TAG}} Here we will change the value with the help of sed command
        ports:
          - containerPort: 3000
---
#gfjhgnnn
apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  selector:
      app: apache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000


